[build]
  functions = "functions"
  publish = "public"

[dev]
  publish = "public"


  # Updated April 9, 2025 - Roy
  # Update
  # Updated sender email to theroycollection@gmail.com - April 10, 2025
  # Testing new email env vars - April 10, 2025
  # Trigger notifications for 2025-04-13 article - April 13, 2025